# Cấu hình latexmk cho đồ án SOICT
# Dùng pdflatex (template dùng \usepackage[utf8]{vietnam}, không tương thích XeLaTeX).
$pdf_mode = 1;
$pdflatex = 'pdflatex -interaction=nonstopmode -synctex=1 -shell-escape %O %S';

# biblatex dùng backend=bibtex (theo template gốc).
$bibtex_use = 2;

# File chính
@default_files = ('DoAn.tex');

# Hỗ trợ glossaries (Tu_viet_tat)
add_cus_dep('glo', 'gls', 0, 'makeglo2gls');
sub makeglo2gls {
    system("makeindex -s \"$_[0].ist\" -t \"$_[0].glg\" -o \"$_[0].gls\" \"$_[0].glo\"");
}

# Dọn dẹp các file phụ
$clean_ext = 'synctex.gz bbl run.xml glo gls glg ist xdy acn acr alg aux fdb_latexmk fls lof lot toc out';
